name: fetch-data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat-data.yml
      - ./gov/noaa/ndbc/postprocess.js
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.ndbc.noaa.gov/activestations.xml
          downloaded_filename: ./gov/noaa/ndbc/active-stations.xml
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.ndbc.noaa.gov/data/latest_obs/latest_obs.txt
          downloaded_filename: ./gov/noaa/ndbc/latest-observations.txt
          postprocess: ./gov/noaa/ndbc/postprocess.js
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: http://api.open-notify.org/iss-now.json
          downloaded_filename: ./iss/iss-now.json
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson
          downloaded_filename: ./gov/usgs/earthquake/all_week.geojson
          postprocess: ./gov/usgs/earthquake/postprocess.js
  create-lp-csv:
    runs-on: ubuntu-latest
    needs: fetch-data
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Create LP and CSV files
      env:
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_BRANCH: ${{ github.ref }}  
      run: |
        cd /tmp
        wget https://dl.influxdata.com/platform/nightlies/influx_nightly_linux_amd64.tar.gz
        tar xvfz influx_nightly_linux_amd64.tar.gz || true
        sudo cp influx_nightly_linux_amd64/{influx,influxd} /usr/local/bin/
        influxd --http-bind-address :8086 --reporting-disabled > /dev/null 2>&1 &
        until curl -s http://localhost:8086/health; do sleep 1; done
        influx setup --host http://localhost:8086 -f -b dummy -o influxdata -u ci_user -p password
        cd $GITHUB_WORKSPACE
        /usr/local/bin/influx write dryrun -f ./gov/noaa/ndbc/latest-observations.csv --format csv --header "#constant measurement,ndbc" --header "#datatype double,double,double,double,double,double,long,double,double,double,double,double,double,double,tag,double,double,double,tag,tag,tag,tag,string,string,string,string,dateTime:number" > ./gov/noaa/ndbc/latest-observations.lp
        /usr/local/bin/influx write -f ./gov/noaa/ndbc/latest-observations.lp -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y)" --raw > ./gov/noaa/ndbc/latest-observations-annotated.csv
        /usr/local/bin/influx bucket delete -n dummy
        /usr/local/bin/influx bucket create -n dummy
        /usr/local/bin/influx write -f ./gov/usgs/earthquake/all_week.lp -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y)" --raw > ./gov/usgs/earthquake/all_week-annotated.csv
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Russ Savage
        author_email: russ@influxdata.com
        message: 'Updating LP and annotated CSV file'