name: fetch-data
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat-data.yml
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch ndbc station data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.ndbc.noaa.gov/activestations.xml
          downloaded_filename: ./gov/noaa/ndbc/active-stations.xml
      - name: Fetch ndbc data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.ndbc.noaa.gov/data/latest_obs/latest_obs.txt
          downloaded_filename: ./gov/noaa/ndbc/latest-observations.txt
          postprocess: ./gov/noaa/ndbc/postprocess.js
      - name: Fetch iss data
        uses: githubocto/flat@v2
        with:
          http_url: http://api.open-notify.org/iss-now.json
          downloaded_filename: ./iss/iss-now.json
          postprocess: ./iss/postprocess.js
      - name: Fetch earthquake data
        uses: githubocto/flat@v2
        with:
          http_url: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson
          downloaded_filename: ./gov/usgs/earthquake/all_week.geojson
          postprocess: ./gov/usgs/earthquake/postprocess.js
      - name: Fetch bitcoin data
        uses: githubocto/flat@v2
        with:
          http_url: https://api.coindesk.com/v1/bpi/currentprice.json
          downloaded_filename: ./com/coindesk/bitcoin/currentprice.json
          postprocess: ./com/coindesk/bitcoin/postprocess.js
      - name: Fetch synoptic data
        uses: githubocto/flat@v2
        with:
          http_url: https://api.synopticdata.com/v2/stations/timeseries?county=san%20francisco,placer,napa&state=ca&recent=60&hfmetars=1&timeformat=%s&vars=soil_temp,snow_depth,solar_radiation,PM_25_concentration,dew_point_temperature,snow_accum,pressure,fosberg_fire_weather_index,wind_speed,air_temp,wind_gust,road_temp,relative_humidity&token=${{ secrets.SYNOPTIC_TOKEN }}
          downloaded_filename: ./com/synopticdata/timeseries-1h-ca-sf-placer-napa.json
      - name: Fetch NORAD data
        uses: githubocto/flat@v2
        with:
          http_url: http://www.celestrak.com/NORAD/elements/stations.txt
          downloaded_filename: ./com/celestrak/norad/stations.txt
  create-lp-csv:
    runs-on: ubuntu-latest
    needs: fetch-data
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup InfluxDB
      uses: influxdata/influxdb-action@v3
      with:
        influxdb_version: latest
        influxdb_org: influxdata
        influxdb_user: ci_user
        influxdb_password: password
        influxdb_bucket: dummy
    - name: Create LP and CSV files
      run: |
        cd $GITHUB_WORKSPACE
        /usr/local/bin/influx write dryrun -f ./gov/noaa/ndbc/latest-observations.csv --format csv --header "#constant measurement,ndbc" --header "#datatype double,double,double,double,double,double,long,double,double,double,double,double,double,double,tag,double,double,double,tag,tag,tag,tag,string,string,string,string,dateTime:number" > ./gov/noaa/ndbc/latest-observations.lp
        /usr/local/bin/influx write -f ./gov/noaa/ndbc/latest-observations.lp -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y) |> drop(columns: [\"_start\",\"_stop\"])" --raw > ./gov/noaa/ndbc/latest-observations-annotated.csv
        /usr/local/bin/influx bucket delete -n dummy
        /usr/local/bin/influx bucket create -n dummy
        /usr/local/bin/influx write -f ./gov/usgs/earthquake/all_week.lp -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y) |> drop(columns: [\"_start\",\"_stop\"])" --raw > ./gov/usgs/earthquake/all_week-annotated.csv
        /usr/local/bin/influx bucket delete -n dummy
        /usr/local/bin/influx bucket create -n dummy
        /usr/local/bin/influx write -f ./com/coindesk/bitcoin/currentprice.lp -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y) |> drop(columns: [\"_start\",\"_stop\"])" --raw > ./com/coindesk/bitcoin/currentprice-annotated.csv
        /usr/local/bin/influx bucket delete -n dummy
        /usr/local/bin/influx bucket create -n dummy
        /usr/local/bin/influx write -f ./iss/iss-now.lp -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -1y) |> drop(columns: [\"_start\",\"_stop\"])" --raw > ./iss/iss-now-annotated.csv
        /usr/local/bin/influx bucket delete -n dummy
        /usr/local/bin/influx bucket create -n dummy
        /usr/local/bin/influx write -f ./iss/iss-now.lp -b dummy
        /usr/local/bin/influx write -f ./iss/iss-historical-annotated.csv --format csv -b dummy
        /usr/local/bin/influx query "from(bucket: \"dummy\") |> range(start: -30d) |> drop(columns: [\"_start\",\"_stop\"])" --raw > ./iss/iss-historical-annotated.csv
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Updating LP and annotated CSV file'
