name: iss-data
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/iss.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: http://api.open-notify.org/iss-now.json
          downloaded_filename: ./iss/iss-now.json
