name: ndbc-data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/ndbc.yml
      - ./gov/noaa/ndbc/postprocess.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.ndbc.noaa.gov/data/latest_obs/latest_obs.txt
          downloaded_filename: ./gov/noaa/ndbc/latest-observations.txt
          postprocess: ./gov/noaa/ndbc/postprocess.js
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.ndbc.noaa.gov/activestations.xml
          downloaded_filename: ./gov/noaa/ndbc/active-stations.xml